### ISSUE TITLE
Use super traits to reduce boiler plate in the EC store.

### ISSUE THREAD

**Issue by ChillFish8** [lnx-search/datacake#24]
Currently, there is a whole bunch of:

```rust
where
    S: Storage + Send + Sync + 'static
```

which can just be simplified.

**Comment by druzn3k** [comment]
@ChillFish8 I'm trying to do this issue, but I have some issue making `test_utils::MemStore` use the super trait. I'm a little green in Rust, but I hope to get the issue solved in just a little more time.

**Comment by ChillFish8** [comment]
I'm not sure what error you're getting, it may be due to some inner handling perhaps, but send the error is the way to go :)

**Comment by druzn3k** [comment]
It's more of a warning. Rust-analyzer complains that it doesn't implement
the trait. But it seems to compile fine. I'm a little puzzled. Can I open a
pr and discuss there? So we have a shared visualization and maybe can help
other noobs :)

Il dom 8 gen 2023, 12:50 Harrison Burt ***@***.***> ha
scritto:

**Comment by ChillFish8** [comment]
yes feel free to open a draft and I can take a look!

**Comment by druzn3k** [comment]
opened a PR @ChillFish8
