### ISSUE TITLE
Writing an actor system on top of datacake

### ISSUE THREAD

**Issue by jvdwrf** [lnx-search/datacake#40]
Hello!

I have been working on an actor system (https://github.com/Zestors/zestors) for some time now, and would like to start working on making a distributed version across a cluster.
Would datacake be a good abstraction for me to build upon? The `datacake_rpc` and the `kv_store` seem like they would reduce a LOT of work. 
I am not planning to start in the near future, but just looking around to find a good future option.

**Comment by ChillFish8** [comment]
You certainly could, you may also find the simulation support useful when testing as well.

**Comment by jvdwrf** [comment]
Yea that also looks great, thanks. I'll experiment further myself.
