### ISSUE TITLE
Bug in replicated-kv causes all nodes to launch with an ID of 1

### ISSUE THREAD

**Issue by ltransom** [lnx-search/datacake#52]
In working with the example, I found the following line to be problematic as it always spawned the node with an ID of 1, irrespective of the command line parameter.  As a newbie, it took me a bit to isolate what was happening.

https://github.com/lnx-search/datacake/blob/2f67f2a151859249162662af4851aaed76888437/examples/replicated-kv/src/main.rs#L41

In my local copy, I changed the line to set the node id per the command line argument:
`let node = DatacakeNodeBuilder::<DCAwareSelector>::new(args.node_id, connection_cfg)`

My question is how do you want bug fixes?  Do want people to open issues like this?  Do you want people to fork and create an upstream PR?

Thank you again for efforts, time, and thoughts.

**Comment by ChillFish8** [comment]
If it's a simple fix feel free to fork and open an upstream PR :)

If it's a more complex issue, like consistency issues or correctness then it probably wants more discussion and debugging, but yeah; for small stuff every little helps!
