### ISSUE TITLE
Hyper 1.0

### ISSUE THREAD

**Issue by FrankReh** [lnx-search/datacake#72]
Is there any interest in moving datacake-rpc from hyper 0.14 to hyper 1.4 and http from 0.2 to 1.1?

I would be willing to take a stab at it if there was interest and a maintainer would be willing to review if I get something to compile.

I have experience with hyper 0.14 and hyper 1.0 came out some time ago now and there are lots of examples of other projects migrating so by now it doesn't feel so daunting.

The change to hyper 1 could have significant benefits to users of datacake-rpc because it puts the transport implementation back in the hands of the user of this crate. Users who want to create a TLS connection or  type of reliable connection should be able to do so.

Hyper 1 exposes new traits, `::rt::{Read, Write}`, that are meant to let the user implement their own transport or at least compile in the transport of their choice and wire up the Read and Write traits support.

Like Hyper does, I could see a helper crate for datacase-rpc to provide the tokio/tcp style from before.

**Comment by ChillFish8** [comment]
Hey 👋 So I am actually working on this, or more specifically I am working towards abstracting the IO layer out a bit, primarily focussing on changing the main IO layer to QUIC, but hopefully making it generic enough so something like hyper could also be supported still.

This hasn't progressed too much though recently as I've had other stuff in the pipeline.

**Comment by FrankReh** [comment]
Okay, I'll leave it then. I look forward to a time I can plug in my own TLS-like TCP connections and not have to fork the entire set of crates. Thanks!

While I don't have anything against QUIC, I prefer TCP connections that have WireGuard-like recognition and secret sharing. I thought your rpc crate, being built on Rkyv, looked great. And maybe the entire set of crates - but I have not groked yet what they all allow. But the idea for a set of tools to build a raft-like negotiation mechanism is very nice.

I'm a proponent of Tokio too, but I think it worth noting that Hyper 1 even abstracted that requirement away.

Look forward to your changes.
